Repository dapr/go-sdk, pull requests merged in 2020-12, with the labels that each got.

#116 proto update
  dapr/proto/common/v1/common.pb.go
  dapr/proto/runtime/v1/appcallback.pb.go
  dapr/proto/runtime/v1/appcallback_grpc.pb.go
  dapr/proto/runtime/v1/dapr.pb.go
  dapr/proto/runtime/v1/dapr_grpc.pb.go
  go.mod
  go.sum
Labels: dependencies

#104 Pub, service invocation methods support structs without serialization
  .vscode/launch.json
  client/client.go
  client/invoke.go
  client/invoke_test.go
  client/pubsub.go
  client/pubsub_test.go
Labels: enhancement

#119 request method verb on service invocation
  .codecov.yaml
  .gitignore
  .vscode/launch.json
  client/client.go
  client/invoke.go
  client/invoke_test.go
  client/state.go
  example/client/main.go
Labels: bug

#123 cleaned up makefiles
  Makefile
  example/Makefile
  example/client/config/pubsub.yaml
  example/client/main.go
  example/config/binding.yaml
  example/config/cron.yaml
  example/config/pubsub.yaml
  example/config/statestore.yaml
  example/pubsub/README.md
  example/pubsub/config/pubsub.yaml
  example/serving/grpc/config/pubsub.yaml
  example/serving/http/config/cron.yaml
  example/serving/http/config/pubsub.yaml
  example/serving/http/config/statestore.yaml
Labels: enhancement

#122 discord notif on release
  .github/workflows/release-on-tag.yaml
Labels: enhancement

#127 feat: Invoke will extract querystring from method
  .gitignore
  client/invoke.go
  client/invoke_test.go
Labels: enhancement
